### ISSUE TITLE
Write brainf* contract

### ISSUE THREAD

**Issue by axic** [ewasm/testnet#13]
There's a transcompiler: https://github.com/uehaj/bf-compiler-webassembly

We could change the
- input to read one byte from calldata
- output to buffer one byte to returndata (the returndata is then flushed when finishing execution)

@jakelang ? :)

**Comment by jakelang** [comment]
oh god

**Comment by axic** [comment]
Done: https://github.com/axic/bf-compiler-webassembly/tree/ewasm

**Comment by lrettig** [comment]
I think I have a new favorite programming language 🤓
