### ISSUE TITLE
Geth support

### ISSUE THREAD

**Issue by axic** [ewasm/testnet#15]
Apparently native ewasm support in geth could be implemented by using [wagon](https://github.com/go-interpreter/wagon) (a wasm interpreter written in Go).

@gballet volunteered to look into this

The tasks are:
- [x] verify that wagon can actually run the official wasm test suite (we don't care about floating point support though)
- [x] integrate wagon into geth
- [x] support all the [EEI methods](https://github.com/ewasm/design/blob/master/eth_interface.md)
- [ ] support all the "vm semantics" (part of it is described [here](https://github.com/ewasm/design/blob/master/vm_semantics.md) but needs to be updated)

For an inspiration see https://github.com/ewasm/hera which does the same thing using binaryen.

**Comment by gballet** [comment]
Having a look at wagon, it seems to do the job but it panics if it encounters a fault. This is a problem if we are going to use it to run contracts, because we can't have geth panic if some contract code is broken.

I have submitted this PR https://github.com/go-interpreter/wagon/pull/53

**Comment by gballet** [comment]
[This gist](https://gist.github.com/gballet/ff599598aaf13f252ed7de2f5c08439f) shows a unit test that demonstrates how to create a module that offers native functions. So far, that requires making some changes to the `wagon` code. I will clean up the code and create a PR this week, to get some feedback from the wagon team.

**Comment by gballet** [comment]
Regarding the `panic`, the wagon team requested a different approach that is tracked in https://github.com/go-interpreter/wagon/pull/57

**Comment by axic** [comment]
Great news!

**Comment by gballet** [comment]
https://github.com/go-interpreter/wagon/pull/58 is the cleaned-up PR asking the wagon people for their comments. I still need to make sure that functions with parameters can be properly called, and then I can start implementing the EEI methods.

**Comment by gballet** [comment]
both PRs are now integrated, I can now proceed with the EEI

**Comment by lrettig** [comment]
@gballet update from today: Working on EEI, done with the easy part. Looking into contracts calling other contracts.

**Comment by gballet** [comment]
Looks like this was missing a reference to the PR that integrates wagon into geth: https://github.com/ethereum/go-ethereum/pull/16957

**Comment by axic** [comment]
Closing this now.
