### ISSUE TITLE
Testnet endpoint is down

### ISSUE THREAD

**Issue by jrainville** [ewasm/testnet#151]
The endpoint (http://ewasm.ethereum.org:8545) seems to be down. Tried to connect to it using Metamask and it never manages to do it.

**Comment by jrainville** [comment]
Closing this as it was an issue with trying to connect from a VM.
I also fixed in Metamask the issue in my main PC by setting the optional option "Chain ID" to 66

**Comment by egroge** [comment]
I am having the same issue. I am not using a VM, and I set the chain ID to 66, but it still will not connect. Any advice?
