### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by jakelang** [ewasm/testnet#19]
When the eWASM testnet goes public it will be important to have a compendium of documentation for working with eWASM and writing contracts.
A decent option for this would be readthedocs.io, which is already used for the Solidity docs.

**Comment by jakelang** [comment]
note: The ethereum magicians fellowship is also talking about moving documentation to another site. Perhaps it could make sense to have ewasm documentation in the same spot as other ethereum docs.

**Comment by jakelang** [comment]
yeah getting rid of this is fine.

**Comment by axic** [comment]
I prefer individual tasks so that the project board can track it.
