### ISSUE TITLE
Devops

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#20]
Devops work related to launching the testnet.

parent of #17

**Comment by lrettig** [comment]
@jwasinger update from yesterday: spent time trying to build a docker-compose that would spin up all the infrastructure (2 miners, faucet, block explorer) as containers on one node.

**Comment by lrettig** [comment]
@cdetrio / @jwasinger update from today:

- Working out kinks in ansible
- Testnet explorer/node up at http://13.95.70.101:3000/, launched from ansible scripts
- Infrastructure is in ewasm testnet ansible playbooks: https://github.com/ethereum/cluster/issues/56 (private devops repo)

**Comment by jwasinger** [comment]
confirmed by @axic , devops work is over! woohoo.  See you guys at devcon, I'm flying off to SEA until then.

**Comment by axic** [comment]
Yeah, it's done!

(Didn't see too much point keeping this open.)
