### ISSUE TITLE
Test scoreboard

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#24]
Runs tests in parallel and shows a running count of how many have passed and failed

**Comment by jwasinger** [comment]
https://github.com/jwasinger/testeth-frontend

**Comment by axic** [comment]
Is this needed? Are we working on this? The assumption is that Hera and Wagon pass all the tests, every time.

**Comment by jwasinger** [comment]
This was specifically proposed for use with evm2wasmJS because running all tests at once during each CI run was too slow.  With evm2wasm-cpp I don't think this is needed.
