### ISSUE TITLE
geth with EVMC

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#36]
- [ ] EVMC support in geth: https://github.com/ethereum/go-ethereum/pull/17050
- [x] EVMC entrypoint alias: https://github.com/ethereum/evmc/pull/36
- [x] evmc_create alias in Hera.

**Comment by gballet** [comment]
actually, #15 is about using github.com/go-interpreter/wagon

**Comment by lrettig** [comment]
@gballet one of the tasks in #15 is "integrate wagon into geth" so I renamed it to a generic "geth support" issue. EVM-C integration would be required for that. We can break it out into more issues if you prefer.

**Comment by chfast** [comment]
This is done.
