### ISSUE TITLE
WAVM support

### ISSUE THREAD

**Issue by lrettig** [ewasm/testnet#41]
Investigate using WAVM for JIT compilation of ewasm

cf. https://github.com/ewasm/hera/issues/158

**Comment by lrettig** [comment]
@jakelang's update from today's standup: Working on getting WABT + WAVM working together

**Comment by lrettig** [comment]
@jakelang any updates here?

**Comment by jakelang** [comment]
@lrettig abstraction layer is ready to go, just hoping that it gets merged before i start piling more on the PR.  also, this issue is a duplicate of ewasm/hera#158

**Comment by lrettig** [comment]
@jakelang Thanks for the update. Yes I'm aware that it's a dupe, this repo is more of a high-level PM repo to track all of the testnet-critical tasks via Waffle with links to other tickets, as I added in the task description above.

**Comment by lrettig** [comment]
@jakelang update from yesterday: figuring out WAVM’s runtime api right now, so i can use it in Hera. going to forget about the cmake stuff for now.

**Comment by lrettig** [comment]
@jakelang update from Friday: still stuck trying to get WAVM to compile with cmake.
