### ISSUE TITLE
in a docker container, some error messages not seen by docker logs 

### ISSUE THREAD

**Issue by cdetrio** [ewasm/testnet#44]
when running cpp-eth in the ewasm testnet dockerfile (https://github.com/ewasm/testnet/pull/17), doing `docker logs` only showed:
```
running eth...
running jsonrpcproxy...
```
But when the eth output was redirected to a file within the docker container, the error message was logged to the file:
```
--peerset argument must not be empty
```

This might be a docker issue, or an issue with cpp-ethereum error logging.

**Comment by axic** [comment]
Is this still a problem?

**Comment by axic** [comment]
@cdetrio still a problem?
