### ISSUE TITLE
Implement codeFromFile in genesis in geth

### ISSUE THREAD

**Issue by axic** [ewasm/testnet#70]
Currently the `genesis.json` support a field `code` which takes a hex string as value.

Goal is to implement `codeFromFile` which takes a file path (relative to the path of the `genesis.json`) and loads the code form there, still considering it as a hex string.

This feature is implemented in aleth already.

**Comment by jwasinger** [comment]
I'm opting to write a script to generate the genesis file programmatically.   I think this would be an easier route than adding this feature to geth.

**Comment by jwasinger** [comment]
Implementing this in Geth should be as simple as changing this line:
https://github.com/ethereum/go-ethereum/blob/7beccb29becf439df7bf4c033a94c019ad25bead/core/genesis.go#L228

**Comment by axic** [comment]
So it seems the geth team is against this and would like to see a genesis modifying tool instead.
