### ISSUE TITLE
Aleth config for the testnet

### ISSUE THREAD

**Issue by gumb0** [ewasm/testnet#88]
With this config I was able to start syncing
https://gist.github.com/gumb0/3415adb568fd94fb5dc65d574f71e117

So far I was able to sync till the block that required Hera invocation.

**Comment by gumb0** [comment]
Currently in block 38880 something is executed differently in Hera comparing to how it was executed when the block was mined, and 58648 gas is consumed instead of 57560 given in the receipt.

The log I get from Hera
```
Executing message in Hera
Metering (input 83 bytes)...
Executing message in Hera
importGlobals
getCallDataSize
callDataCopy 110008 0 53
useGas 2656
finish 1102d8 6a
Metering done (output 106 bytes, used 2670 gas)
importGlobals
useGas 4
finish 0 0
Zero-length memory load from offset 0x0
```

**Comment by gumb0** [comment]
With this fix https://github.com/ethereum/aleth/pull/5329 I was able to sync to the top.

**Comment by axic** [comment]
@gumb0 @chfast @jwasinger is this still a valid genesis?

**Comment by axic** [comment]
Actually since #91 the forks start at 0.

**Comment by axic** [comment]
@gumb0 is this issue still relevant? Have you compared it against https://github.com/ewasm/testnet/blob/master/ewasm-testnet-aleth-config.json ?

Can you close this issue if it is not relevant anymore?

**Comment by gumb0** [comment]
If the forks start at 0, it won't work, but you can use it as a starting point to create a relevant config.

**Comment by axic** [comment]
> If the forks start at 0, it won't work, but you can use it as a starting point to create a relevant config.

@gumb0 can you explain the reason?

**Comment by gumb0** [comment]
I mean it will if you change it, the particular config linked linked in this issue obviously won't work
