### ISSUE TITLE
Build Hera

### ISSUE THREAD

**Issue by khaidv** [ewasm/testnet#89]
I built hera follow as the tutorial but not work for me. Is there anyone help me??
![image](https://user-images.githubusercontent.com/30402264/47498249-eb516f00-d886-11e8-9733-3ad862a7e9e4.png)

 Thanks in advance!!

**Comment by axic** [comment]
@khaidv sorry for the delay, can you tell us what version of hera you are using and is your compiler version?

**Comment by khaidv** [comment]
> @khaidv sorry for the delay, can you tell us what version of hera you are using and is your compiler version?
Hera can't build on Windows??.  I used hera library and interact with go-ethereum as follow the tutorial. But there is an error : can't open hera.so while i run geth using -synmode=full.

**Comment by axic** [comment]
Can you please tell what repository you tried to build? The paths seems to be `go-ethereum/hera/evmc`, which we do not have.

**Comment by khaidv** [comment]
> Can you please tell what repository you tried to build? The paths seems to be `go-ethereum/hera/evmc`, which we do not have.

Could you please give me the repositories of go-ethereum and hera?

**Comment by axic** [comment]
Everything is in the readme: https://github.com/ewasm/testnet

But I'm still intrigued what did you try to compile.

**Comment by khaidv** [comment]
> Everything is in the readme: https://github.com/ewasm/testnet
> 
> But I'm still intrigued what did you try to compile.

I built it like 1 month ago. I can't remember what version of hera I use :)). Errors is the above image

**Comment by axic** [comment]
Ok, I'm going to close this then. Please check back tomorrow when we plan to have a final working set of instructions for building.
