### ISSUE TITLE
Ensure truffle works with EVM on the testnet

### ISSUE THREAD

**Issue by axic** [ewasm/testnet#97]

**Comment by axic** [comment]
Sample instructions: #98

**Comment by lrettig** [comment]
For some odd reason I can't get truffle to work with HDWalletProvider (necessary to supply an account with gas for the deploy). Logged https://github.com/trufflesuite/truffle/issues/1429.

**Comment by lrettig** [comment]
Issue was resolved. Confirmed that it worked in staging with an out-of-the-box sample truffle app (metacoin):

http://40.114.207.112/explorer/tx/0x0ccda82ef34f18ac59cc8a1e017b091dd00e7159c620ec88b48226be82d636f7
http://40.114.207.112/explorer/tx/0xd431b6543ec883f432ba01fb0576a0ece3c22c33c01208a3b8f6f2f8a6ebe58e
http://40.114.207.112/explorer/tx/0x1f2dcef82a1bcc3b9541403ab365836682564ba0497683c35775dbdb0037930e
http://40.114.207.112/explorer/tx/0x17040fcb158ded76d1a70e4f4247d6f9848d72d2e46bd328153e4f4c0502c795

**Comment by axic** [comment]
Great! Perhaps worth documenting the need for that `web-one` thing?
